apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anchore-engine
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://github.com/jimmyTchoffo/argocd-anchore.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
